#!/usr/bin/env ruby
require "terminalwire/client"

Zeitwerk::Loader.eager_load_all

begin
  Terminalwire::Client::Exec.start
rescue Interrupt
  exit 0
rescue Terminalwire::Error => e
  $stderr.puts e.message
  $stderr.puts e.cause.full_message if ENV["TERMINALWIRE_DEBUG"] && e.cause
  exit 1
end
