#!/usr/bin/env ruby
require "terminalwire/client"

begin
  Terminalwire::Client.websocket(url: "wss://terminalwire.com/terminal")
rescue Terminalwire::Error => e
  $stderr.puts e.message
  $stderr.puts e.cause.full_message if ENV["TERMINALWIRE_DEBUG"] && e.cause
  exit 1
end
