name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false

    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3 --verbose

    - name: Run RSpec
      run: bundle exec rspec --format documentation

  package:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby:
          - '3.3.0'

    runs-on: ${{ matrix.os }}
    name: Package ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3 --verbose

      - name: Run Tebako
        run: bundle exec rake package:build

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: build/*
